Repository laramies/theHarvester, pull requests merged in 2019-10, with the labels that each got.

#328 Rename the variables in myparser.py
  theHarvester/parsers/myparser.py
Labels: hacktoberfest

#323 Simplify `unique` method in myParser
  theHarvester/parsers/myparser.py
Labels: hacktoberfest

#331 Implemented -b all
  theHarvester/__main__.py
Labels: Enhancement, hacktoberfest

#312 update deps, removed censys and removed uneeded code
  .github/FUNDING.yml
  .github/ISSUE_TEMPLATE/issue-template.md
  .github/workflows/theHarvester.yml
  .gitignore
  .travis.yml
  Pipfile
  Pipfile.lock
  README.md
  api-keys.yaml
  mypy.ini
  requirements.txt
  setup.cfg
  theHarvester/__main__.py
  theHarvester/discovery/IPy.py
  theHarvester/discovery/__init__.py
  theHarvester/discovery/censys.py
  theHarvester/discovery/duckduckgosearch.py
  theHarvester/discovery/s3_scanner.py
  theHarvester/discovery/spyse.py
  theHarvester/discovery/suip.py
  theHarvester/lib/core.py
  theHarvester/lib/hostchecker.py
  theHarvester/parsers/censysparser.py
Labels: Enhancement, hacktoberfest

#338 Fix mypy error for github module
  theHarvester/discovery/githubcode.py
Labels: bug_fix, hacktoberfest

#350 Fix mypy error for github module
  theHarvester/discovery/githubcode.py
Labels: Bug, hacktoberfest

#340 Externalise code repetition to method
  tests/test_theHarvester.py
  theHarvester/__main__.py
Labels: Enhancement, hacktoberfest
